# Generated by Django 4.1 on 2022-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="patient_entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gender", models.CharField(blank=True, default="", max_length=20)),
                ("Age", models.IntegerField()),
                ("Race", models.CharField(blank=True, default="", max_length=20)),
                ("Diagnosis", models.CharField(blank=True, default="", max_length=256)),
                ("MD", models.CharField(blank=True, default="", max_length=20)),
                ("Assignment", models.CharField(blank=True, default="", max_length=20)),
                ("EMR", models.CharField(blank=True, default="", max_length=20)),
                ("LOS", models.IntegerField()),
                ("RAR", models.IntegerField()),
                ("A", models.IntegerField()),
                ("B", models.IntegerField()),
                ("C", models.IntegerField()),
                ("D", models.IntegerField()),
                ("E", models.IntegerField()),
                ("F", models.IntegerField()),
                ("G", models.IntegerField()),
                ("H", models.IntegerField()),
                ("I", models.IntegerField()),
                ("J", models.IntegerField()),
                ("K", models.IntegerField()),
                ("L", models.IntegerField()),
                ("M", models.IntegerField()),
                ("N", models.IntegerField()),
                ("O", models.IntegerField()),
                ("P", models.IntegerField()),
                ("Q", models.IntegerField()),
                ("R", models.IntegerField()),
                ("S", models.IntegerField()),
                ("T", models.IntegerField()),
                ("U", models.IntegerField()),
                ("V", models.IntegerField()),
                ("W", models.IntegerField()),
                ("X", models.IntegerField()),
                ("Y", models.IntegerField()),
                ("Z", models.IntegerField()),
                ("AA", models.IntegerField()),
                ("AB", models.IntegerField()),
                ("AC", models.IntegerField()),
                ("AD", models.IntegerField()),
                ("PsychotropicMedications", models.IntegerField()),
                ("Administrations", models.IntegerField()),
                (
                    "TherapeuticGuidances",
                    models.CharField(blank=True, default="", max_length=20),
                ),
            ],
        ),
    ]
